### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by hyunjun** [gruter/cloumon-elk#1]
Very minor, however there is a typo in make-tarball.sh like below;

```
echo "Deleting existing tablls"
```

It was tarballs, right?

**Comment by ykko** [comment]
Good catch! We'll fix the typo.

Thanks a lot.
Youngkyong
1. 2. 11. 오후 3:46에 hyunjun 이(가) 쓴 글:

**Comment by keybod** [comment]
Fixed!
Thanks @hyunjun.
